config/routes.rb
DailyBehavior::Application.routes.draw do
  
  resources :student_data
  resources :prospects
  resources :behaviors do
    collection do
      get 'new_single_today'
      get 'new_whole_day'
      get 'new_single_choose'
    end
  end

  resources :students do
    member do
      get 'show_table'
      get 'show_graph'
    end
  end
  resources :password_resets
  resources :users
  resources :sessions,   only: [:new, :create, :destroy]

  root :to => 'static_pages#home'
  match 'help',    to: 'static_pages#help',    via: 'get'
  match 'about',   to: 'static_pages#about',   via: 'get'
  match 'contact', to: 'static_pages#contact', via: 'get'
  match 'signup',  to: 'prospects#new',        via: 'get'

  match 'signin',  to: 'sessions#new',         via: 'get'
  match 'signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/student.rb
class Student < ActiveRecord::Base
	belongs_to :user
	has_many :behaviors, dependent: :destroy
	validates :user_id, presence: true
	validates :name, presence: true
	validates :student_id, presence: true, uniqueness: true
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :signed_in_user

	def new
		@student = Student.new
	end

	def create
		@student = current_user.students.build(student_params)
    	if @student.save
      		flash[:success] = "Student created!"
      		redirect_to root_url
    	else
      		flash[:error] = "Student creation unsuccessful!"
      		render 'new'
    	end
	end

	def show
		@student = Student.find(params[:id])
		@user = User.find_by(id: @student.user_id)
		@behaviors = @student.behaviors.paginate(page: params[:page])
		@todaysBehaviors = todays_behaviors()
		if !@todaysBehaviors.any?
			(0..23).each do |i|
				@todaysBehaviors[i] = 0
			end
		end
		@thisWeeksBehaviors = this_weeks_behaviors()
		if !@thisWeeksBehaviors.any?
			(0..23).each do |i|
				@thisWeeksBehaviors[i] = 0
			end
		end
	end

	def show_graph
		@student = Student.find(params[:id])
		@user = User.find_by(id: @student.user_id)
		@behaviors = @student.behaviors.paginate(page: params[:page])
	#	@todaysBehaviors = todays_behaviors()
	#	if !@todaysBehaviors.any?
	#		(0..3).each do |i|
	#			@todaysBehaviors[i] = 0
	#		end
	#	end
		@thisWeeksBehaviors = this_weeks_behaviors()
		if !@thisWeeksBehaviors.any?
			(0..3).each do |i|
				@thisWeeksBehaviors[i] = 0
			end
		end
		respond_to do |format|
			format.js			
		end
	end

	def show_table
		@student = Student.find(params[:id])
		@user = User.find_by(id: @student.user_id)
		@behaviors = @student.behaviors.paginate(page: params[:page])
		@todaysBehaviors = todays_behaviors()
		if !@todaysBehaviors.any?
			(0..3).each do |i|
				@todaysBehaviors[i] = 0
			end
		end
		@thisWeeksBehaviors = this_weeks_behaviors()
		if !@thisWeeksBehaviors.any?
			(0..23).each do |i|
				@thisWeeksBehaviors[i] = 0
			end
		end
		respond_to do |format|
			format.js 
		end
	end

	def destroy
    	    	
  	end

	private
		def student_params
			params.require(:student).permit(:name, :student_id)
		end

		def todays_behaviors(t = Time.now)
			dailys = @student.behaviors.where(
					"record_time > ? AND record_time < ?", 
						t.at_beginning_of_day, t.tomorrow.at_beginning_of_day)
							.pluck(:pos1, :neg1, :neg2, :cor1).to_a
			dailys.transpose.map &:sum
		end

		def this_weeks_behaviors(t = Time.now)
			tableBehaviors = @student.behaviors.where(
					"record_time > ? AND record_time < ?", 
						Time.now.at_beginning_of_week, Time.now.at_end_of_week)
			@tableBehaviors = tableBehaviors.paginate(page: params[:page]) 
			weeklys = tableBehaviors.pluck(:pos1, :pos2, :pos3, :pos4, :neg1, :neg2, :neg3, :neg4, 
								:neg5, :neg6, :neg7, :neg8, :neg9, :neg10, :neg11, :neg12, 
								:neg13, :neg14, :neg15, :neg16, :cor1, :cor2, :cor3, :cor4).to_a			
			@thisWeeksTotal = weeklys.count
			weeklys.transpose.map &:sum
			
		end
end

app/views/students/_info.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :student_id %>
<%= f.text_field :student_id %>


app/views/students/_show_graph.html.erb
<%= javascript_include_tag 'charts' %>
		<% if @student.behaviors.any? %>
			<%= chart_tag('student_graph', 600, { :theseBehaviors => @thisWeeksBehaviors, :thisTotal => @thisWeeksTotal }) %>
			<p></p>
			
		<% end %>
		

app/views/students/_show_graphOLD.html.erb

		<% if @student.behaviors.any? %>
			<div id="mychart"></div>
			<p></p>
			
		<% end %>
		<script type="text/javascript" src="//www.google.com/jsapi"></script>
    <script type="text/javascript">
      google.load('visualization', '1', {packages: ['corechart']});
    </script>
    <script type="text/javascript">
      google.setOnLoadCallback(drawChart);
      function drawChart() {
      	 // Create the data table.
      var data = new google.visualization.DataTable();
      data.addColumn('string', 'Behavior');
      data.addColumn('number', 'Number');
      data.addRows([
        ['Positive', <%= @thisWeeksBehaviors[0] %>],
        ['Negative1', <%= @thisWeeksBehaviors[1] %>],
        ['Negative2', <%= @thisWeeksBehaviors[2] %>], 
        ['Correction', <%= @thisWeeksBehaviors[3] %>],
      ]);

      // Set chart options
      var options = {'title':'Behaviors',
      				 'legend': 'none',
      				 'vAxis': { maxValue:  <%= @thisWeeksTotal %>, gridlines: { color: '#333', count: -1 } },
                     'width':400,
                     'height':300};

      // Instantiate and draw our chart, passing in some options.
      var chart = new google.visualization.ColumnChart(document.getElementById('mychart'));
      chart.draw(data, options);
    }
    </script>
		

app/views/students/_show_graph_test.html.erb

		<% if @student.behaviors.any? %>
			<div id="mychart"></div>
			<p></p>
			
		<% end %>
		<script type="text/javascript" src="//www.google.com/jsapi"></script>
    

app/views/students/_show_table.html.erb

		<% if @thisWeeksTotal != 0 %>
      		<h3>Behaviors Recorded This Week (<%= @thisWeeksTotal %>)</h3>
      		<table class="table table-striped table-condensed">
				<tr>
					<th>Time</th>
					<th>On Task</th>
					<th>Positive Interactions</th>
					<th>Safety</th>
					<th>B.I.P. Goal</th>
					<th>Defiant</th>
					<th>Disrespectful</th>
					<th>Disruptive</th>
					<th>Property Distruction</th>
					<th>Threatening</th>
					<th>Obsenity</th>
					<th>Physical Aggression</th>
					<th>Verbal Aggression</th>
					<th>AWOL</th>
					<th>Sleeping</th>
					<th>Provoking/Mocking</th>
					<th>Self-Injurious</th>
					<th>Repeat Offense</th>
					<th>B.I.P. Goal</th>
					<th>Tardy</th>
					<th>Other</th>
					<th>Time Away</th>
					<th>Time Out</th>
					<th>Seclusion</th>
					<th>Restraint</th>
					<th></th>
					<th></th>
				</tr>
				<tr>
					<td>This Week's Totals</td>
					<td><%= @thisWeeksBehaviors[0] %></td>
					<td><%= @thisWeeksBehaviors[1] %></td>
					<td><%= @thisWeeksBehaviors[2] %></td>
					<td><%= @thisWeeksBehaviors[3] %></td>
					<td><%= @thisWeeksBehaviors[4] %></td>
					<td><%= @thisWeeksBehaviors[5] %></td>
					<td><%= @thisWeeksBehaviors[6] %></td>
					<td><%= @thisWeeksBehaviors[7] %></td>
					<td><%= @thisWeeksBehaviors[8] %></td>
					<td><%= @thisWeeksBehaviors[9] %></td>
					<td><%= @thisWeeksBehaviors[10] %></td>
					<td><%= @thisWeeksBehaviors[11] %></td>
					<td><%= @thisWeeksBehaviors[12] %></td>
					<td><%= @thisWeeksBehaviors[13] %></td>
					<td><%= @thisWeeksBehaviors[14] %></td>
					<td><%= @thisWeeksBehaviors[15] %></td>
					<td><%= @thisWeeksBehaviors[16] %></td>
					<td><%= @thisWeeksBehaviors[17] %></td>
					<td><%= @thisWeeksBehaviors[18] %></td>
					<td><%= @thisWeeksBehaviors[19] %></td>
					<td><%= @thisWeeksBehaviors[20] %></td>
					<td><%= @thisWeeksBehaviors[21] %></td>
					<td><%= @thisWeeksBehaviors[22] %></td>
					<td><%= @thisWeeksBehaviors[23] %></td>
					<td><%= @thisWeeksTotal %></td>
					<td></td>
				</tr>
				<% for behavior in @tableBehaviors %>
				<tr>
					<td><%= behavior.record_time.to_s() %></td>
					<td><%= behavior.pos1 %></td>
					<td><%= behavior.pos2 %></td>
					<td><%= behavior.pos3 %></td>
					<td><%= behavior.pos4 %></td>
					<td><%= behavior.neg1 %></td>
					<td><%= behavior.neg2 %></td>
					<td><%= behavior.neg3 %></td>
					<td><%= behavior.neg4 %></td>
					<td><%= behavior.neg5 %></td>
					<td><%= behavior.neg6 %></td>
					<td><%= behavior.neg7 %></td>
					<td><%= behavior.neg8 %></td>
					<td><%= behavior.neg9 %></td>
					<td><%= behavior.neg10 %></td>
					<td><%= behavior.neg11 %></td>
					<td><%= behavior.neg12 %></td>
					<td><%= behavior.neg13 %></td>
					<td><%= behavior.neg14 %></td>
					<td><%= behavior.neg15 %></td>
					<td><%= behavior.neg16 %></td>
					<td><%= behavior.cor1 %></td>
					<td><%= behavior.cor2 %></td>
					<td><%= behavior.cor3 %></td>
					<td><%= behavior.cor4 %></td>
					<td><%= link_to "Delete", behavior, method: :delete, data: { confirm: "You sure?" } %></td>
					<td><%= link_to "Edit", edit_behavior_path(behavior) %></td>
				</tr>
				<% end %>
			</table>
			<%= will_paginate @tableBehaviors %>
    	<% end %>
		

app/views/students/_student.html.erb
<li>
	<span class="studentName"><%= link_to student.name, student %></span>
	<span class="studentId"><%= student.student_id %></span>
</li>

app/views/students/new.html.erb
<% provide(:title, 'Create new student') %>
<h1>Create new student</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@student) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

			<%= f.label :name %>
			<%= f.text_field :name %>

			<%= f.label :student_id, "Student ID" %>
			<%= f.text_field :student_id %>

			<%= f.submit "Create student", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/students/show.html.erb
<% provide(:title, @student.name) %>
<div class="row">
	<aside class="span3">
		<section>
			<h1 class="students">
				<%= @student.name %>
			</h1>
			<h2 class="students">
				<%= @student.student_id  %>
			</h2>
		</section>
		<% if current_user?(@user) %>
			<% current_student %>
			<p><%= link_to "Record student behavior", new_behavior_path %></p>
		<% end %>
		<section>
			
		</section>
	</aside>
	<div class="span9">
		<ul class="nav nav-tabs">
			<li class="active" id="studentShowTab1">
				<%= link_to "This Week's Graph", show_graph_student_path, remote: true %>
			</li>
			<li id="studentShowTab2">
				<%= link_to "This Week's Table", show_table_student_path, remote: true %>

			</li>
		</ul>
		<div id="studentShowContent">
			<%= render "show_graph" %>
		</div>
		
		
	</div>
</div>

app/views/students/showGRAPH.html.erb
<% provide(:title, @student.name) %>
<% require 'gchart' %>
<div class="row">
	<aside class="span4">
		<section>
			<h1 class="students">
				<%= @student.name %>
			</h1>
			<h2 class="students">
				<%= @student.student_id  %>
			</h2>
		</section>
		<% if current_user?(@user) %>
			<% current_student %>
			<p><%= link_to "Record student behavior", new_behavior_path %></p>
		<% end %>
	</aside>
	<div class="span8">
		<% if @student.behaviors.any? %>
			<%= image_tag(Gchart.bar(:data => @thisWeeksBehaviors,
									:theme => :thirty7signals,
									:max_value => @thisWeeksTotal,
									
									:bar_width_and_spacing => [30,25],
									
									:axis_with_labels => ['x,y'],
									:axis_labels => ['Positive|Negative1|Negative2|Correction'],
									
									:title => "Behaviors",
									:size => '600x400'

									)) %>
		<% end %>
		
	</div>
</div>

app/views/students/showOLD.html.erb
<% provide(:title, @student.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1 class="students">
				<%= @student.name %>
			</h1>
			<h2 class="students">
				<%= @student.student_id  %>
			</h2>
		</section>
		<% if current_user?(@user) %>
			<% current_student %>
			<p><%= link_to "Record student behavior", new_behavior_path %></p>
		<% end %>
	</aside>
	<div class="span8">
		<% if @student.behaviors.any? %>
      		<h3>Behaviors (<%= @student.behaviors.count %>)</h3>
      		<table class="table table-stripped table-condensed">
				<tr>
					<th>Time</th>
					<th>Positive</th>
					<th>Negative1</th>
					<th>Negative2</th>
					<th>Correction</th>
					<th></th>
				</tr>
				<% for behavior in @behaviors %>
				<tr>
					<td><%= behavior.created_at.in_time_zone("Central Time (US & Canada)").to_s(:long) %></td>
					<td><%= behavior.pos1 %></td>
					<td><%= behavior.neg1 %></td>
					<td><%= behavior.neg2 %></td>
					<td><%= behavior.cor1 %></td>
					<td><%= link_to "Edit", @behavior %></td>
				</tr>
				<% end %>
			</table>
			<%= will_paginate @behaviors %>
    	<% end %>
		<!--
		<div id="exampleGrid" class="handsontable"></div>
			<script type="text/javascript">
			var myData = [
			   ["", "Kia", "Nissan", "Toyota", "Honda"],
			   ["2008", 10, 11, 12, 13],
			   ["2009", 20, 11, 14, 13],
			   ["2010", 30, 15, 12, 13]
			   ];

			$("#exampleGrid").handsontable({
			   data: myData,
			   startRows: 5,
			   startCols: 5,
			   minSpareCols: 1,
			   //always keep at least 1 spare row at the right
			   minSpareRows: 1,
			   //always keep at least 1 spare row at the bottom,
			   rowHeaders: true,
			   colHeaders: true,
			   contextMenu: true
			});

			$("exampleGrid table").addClass("table table-striped");
			</script>
		-->
	</div>
</div>

app/views/students/show_graph.js.erb
$("#studentShowTab1").addClass("active");
$("#studentShowTab2").removeClass("active");
$("#studentShowContent").html("<%= escape_javascript(render('show_graph')) %>");

app/views/students/show_table.js.erb
$("#studentShowTab1").removeClass("active");
$("#studentShowTab2").addClass("active");
$("#studentShowContent").html("<%= escape_javascript(render('show_table')) %>");
$('.pagination a').attr('data-remote', 'true');