config/routes.rb
DailyBehavior::Application.routes.draw do
  
  resources :student_data
  resources :prospects
  resources :behaviors do
    collection do
      get 'new_single_today'
      get 'new_whole_day'
      get 'new_single_choose'
    end
  end

  resources :students do
    member do
      get 'show_table'
      get 'show_graph'
    end
  end
  resources :password_resets
  resources :users
  resources :sessions,   only: [:new, :create, :destroy]

  root :to => 'static_pages#home'
  match 'help',    to: 'static_pages#help',    via: 'get'
  match 'about',   to: 'static_pages#about',   via: 'get'
  match 'contact', to: 'static_pages#contact', via: 'get'
  match 'signup',  to: 'prospects#new',        via: 'get'

  match 'signin',  to: 'sessions#new',         via: 'get'
  match 'signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/behavior.rb
class Behavior < ActiveRecord::Base
	belongs_to :student
	default_scope -> { order('record_time DESC') }
	validates :student_id, presence: true

	
end

app/controllers/behaviors_controller.rb
class BehaviorsController < ApplicationController
  before_action :signed_in_user

  def new
    @student = Student.find_by(id: session[:this_student_id])
  	@behavior = Behavior.new
    @today = Time.now
    @behavior.pos1 = 1
    @behavior.pos2 = 1
    @behavior.pos3 = 1
    @behavior.pos4 = 1
  end

  def create
    @student = Student.find_by(id: session[:this_student_id])
    respond_to do |format|
      format.js {
        @behaviors = params[:behaviors].values
        @behaviors.each do |behavior_params|
          @behavior = @student.behaviors.create(behavior_params)
        end
      }
      format.html{
        @behavior = @student.behaviors.create(behavior_params)
        redirect_to @student
      }
    end
    
    

        
    # if @behavior.save
    #    flash[:success] = "Student behavior saved!"
    #    respond_to do |format|
    #      format.html { redirect_to @student }
    #      format.js
    #    end
    # else
    #    flash[:error] = "Student behavior NOT saved! Please try again."
    #    render 'static_pages/home'
    # end
    
  end

  def new_single_today
    respond_to do |format|
      format.js {
        @student = Student.find_by(id: session[:this_student_id])
        @behavior = Behavior.new
        @today = Time.now
        @behavior.pos1 = 1
        @behavior.pos2 = 1
        @behavior.pos3 = 1
        @behavior.pos4 = 1
      }
    end
  end

  def new_whole_day
    respond_to do |format|
      format.js {
        @student = Student.find_by(id: session[:this_student_id])
        @behavior = Behavior.new
        @today = Time.now
      }
    end
  end

  def new_single_choose
    respond_to do |format|
      format.js {
        @student = Student.find_by(id: session[:this_student_id])
        @behavior = Behavior.new
        @today = Time.now
        @behavior.pos1 = 1
        @behavior.pos2 = 1
        @behavior.pos3 = 1
        @behavior.pos4 = 1
      }
    end
  end

  def destroy
      @student = Student.find_by(id: session[:this_student_id])
      @behavior = @student.behaviors.find(params[:id])
      if @behavior.destroy
        flash[:success] = "Behavior deleted."
        redirect_to @student
      else
        flash![:error] = "Behavior NOT deleted."
      end
      
    end

  def index
  end

  def edit
    @behavior = Behavior.find(params[:id])
  end

  def show
    @behavior = Behavior.find(params[:id])
  end

  def update
    @student = Student.find_by(id: session[:this_student_id])
    @behavior = Behavior.find(params[:id])
    if @behavior.update_attributes(behavior_params)
      # Handle a successfuol update.
      flash[:success] = "Behavior updated"
      redirect_to @student
    else
      flash![:error] = "Something went wrong!"
      render 'edit'
    end
  end

  private
    def behavior_params
      params.require(:behavior).permit(:pos1, :pos2, :pos3, :pos4, :neg1, :neg2, :neg3, :neg4, 
                :neg5, :neg6, :neg7, :neg8, :neg9, :neg10, :neg11, :neg12, 
                :neg13, :neg14, :neg15, :neg16, :cor1, :cor2, :cor3, :cor4, :record_time)
    end
end

app/views/behaviors/_behavior.html.erb

<table>
	<tr>
		<th>Time</th>
		<th>Positive</th>
		<th>Negative1</th>
		<th>Negative2</th>
		<th>Correction</th>
		<th></th>
	</tr>
	<% for behavior in @behaviors %>
	<tr>
		<td><%= behavior.created_at.in_time_zone("Central Time (US & Canada)").to_s(:long) %></td>
		<td><%= behavior.pos1 %></td>
		<td><%= behavior.neg1 %></td>
		<td><%= behavior.neg2 %></td>
		<td><%= behavior.cor1 %></td>
		<td><%= link_to "Edit", @behavior, :confirm => 'Are you sure?', :method => :create %></td>
	</tr>
	<% end %>
</table>

app/views/behaviors/_behaviorOLD.html.erb

<li>
	<h2><%= behavior.created_at.in_time_zone("Central Time (US & Canada)").to_s(:long) %></h2>
	<span class="studentName"><%= behavior.pos1_name %></span>
	<span class="studentId">
		<% if behavior.pos1 %>
			1
		<% else %>	
			0
		<% end %>
	</span>
	<span class="studentName"><%= behavior.neg1_name %></span>
	<span class="studentId">
		<% if behavior.neg1 %>
			1
		<% else %>	
			0
		<% end %>
	</span>
	<span class="studentName"><%= behavior.neg2_name %></span>
	<span class="studentId">
		<% if behavior.neg2 %>
			1
		<% else %>	
			0
		<% end %>
	</span>
	<span class="studentName"><%= behavior.cor1_name %></span>
	<span class="studentId">
		<% if behavior.cor1 %>
			1
		<% else %>	
			0
		<% end %>
	</span>
</li>

app/views/behaviors/_edit_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="control-group">
	<%= f.label :pos1, "On Task", :class =>  "control-label"  %>
	<div class="controls">
		<%= f.select(:pos1, options_for_select([['0', 0], ['1', 1]], @behavior.pos1))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :pos2, "Positive Interactions", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:pos2, options_for_select([['0', 0], ['1', 1]], @behavior.pos2))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :pos3, "Safety", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:pos3, options_for_select([['0', 0], ['1', 1]], @behavior.pos3))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :pos4, "B.I.P. Goal", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:pos4, options_for_select([['0', 0], ['1', 1]], @behavior.pos4))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg1, "Defiant", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg1, options_for_select([['0', 0], ['1', 1]], @behavior.neg1))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg2, "Disrespectful", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg2, options_for_select([['0', 0], ['1', 1]], @behavior.neg2))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg3, "Disruptive", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg3, options_for_select([['0', 0], ['1', 1]], @behavior.neg3))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg4, "Property Distruction", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg4, options_for_select([['0', 0], ['1', 1]], @behavior.neg4))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg5, "Threatening", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg5, options_for_select([['0', 0], ['1', 1]], @behavior.neg5))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg6, "Obsenity", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg6, options_for_select([['0', 0], ['1', 1]], @behavior.neg6))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg7, "Physical Aggression", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg7, options_for_select([['0', 0], ['1', 1]], @behavior.neg7))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg8, "Verbal Aggression", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg8, options_for_select([['0', 0], ['1', 1]], @behavior.neg8))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg9, "AWOL", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg9, options_for_select([['0', 0], ['1', 1]], @behavior.neg9))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg10, "Sleeping", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg10, options_for_select([['0', 0], ['1', 1]], @behavior.neg10))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg11, "Provoking/Mocking", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg11, options_for_select([['0', 0], ['1', 1]], @behavior.neg11))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg12, "Self-Injurious", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg12, options_for_select([['0', 0], ['1', 1]], @behavior.neg12))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg13, "Repeat Offense", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg13, options_for_select([['0', 0], ['1', 1]], @behavior.neg13))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg14, "B.I.P. Goal", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg14, options_for_select([['0', 0], ['1', 1]], @behavior.neg14))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg15, "Tardy", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg15, options_for_select([['0', 0], ['1', 1]], @behavior.neg15))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg16, "Other", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg16, options_for_select([['0', 0], ['1', 1]], @behavior.neg16))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :cor1, "Time Away", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:cor1, options_for_select([['0', 0], ['1', 1]], @behavior.cor1))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :cor2, "Time Out", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:cor2, options_for_select([['0', 0], ['1', 1]], @behavior.cor2)) %>
	</div>
</div>
<div class="control-group">
	<%= f.label :cor3, "Seclusion", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:cor3, options_for_select([['0', 0], ['1', 1]], @behavior.cor3))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :cor4, "Restraint", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:cor4, options_for_select([['0', 0], ['1', 1]], @behavior.cor4))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :record_time, "Behavior Record Time", :class => "control-label" %>
	<div class="controls">
		<%= f.datetime_select :record_time, { ampm: true, default: @behavior.record_time, discard_year: true }%>
	</div>
</div>


app/views/behaviors/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="control-group">
	<%= f.label :pos1, "On Task", :class =>  "control-label"  %>
	<div class="controls">
		<%= f.select(:pos1, options_for_select([['0', 0], ['1', 1]], 1))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :pos2, "Positive Interactions", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:pos2, options_for_select([['0', 0], ['1', 1]], 1))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :pos3, "Safety", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:pos3, options_for_select([['0', 0], ['1', 1]], 1))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :pos4, "B.I.P. Goal", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:pos4, options_for_select([['0', 0], ['1', 1]], 1))  %>
	</div>	
</div>
<div class="control-group">
	<%= f.label :neg1, "Defiant", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg1, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg2, "Disrespectful", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg2, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg3, "Disruptive", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg3, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg4, "Property Distruction", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg4, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg5, "Threatening", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg5, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg6, "Obsenity", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg6, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg7, "Physical Aggression", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg7, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg8, "Verbal Aggression", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg8, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg9, "AWOL", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg9, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg10, "Sleeping", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg10, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg11, "Provoking/Mocking", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg11, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg12, "Self-Injurious", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg12, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg13, "Repeat Offense", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg13, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg14, "B.I.P. Goal", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg14, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg15, "Tardy", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg15, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg16, "Other", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg16, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :cor1, "Time Away", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:cor1, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :cor2, "Time Out", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:cor2, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :cor3, "Seclusion", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:cor3, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :cor4, "Restraint", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:cor4, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :record_time, "Behavior Record Time", :class => "control-label" %>
	<div class="controls">
		<%= f.datetime_select :record_time, { ampm: true, default: @behavior.record_time }%>
	</div>
</div>


app/views/behaviors/_single_today_new.html.erb

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@behavior, html: {class: "form", role: "form"}) do |f| %>
			<%= render 'today_checkboxes', f: f %>
			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/behaviors/_today_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="control-group">
	<%= f.label :pos1, "On Task", :class =>  "control-label"  %>
	<div class="controls">
		<%= f.select(:pos1, options_for_select([['0', 0], ['1', 1]], 1))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :pos2, "Positive Interactions", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:pos2, options_for_select([['0', 0], ['1', 1]], 1))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :pos3, "Safety", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:pos3, options_for_select([['0', 0], ['1', 1]], 1))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :pos4, "B.I.P. Goal", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:pos4, options_for_select([['0', 0], ['1', 1]], 1))  %>
	</div>	
</div>
<div class="control-group">
	<%= f.label :neg1, "Defiant", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg1, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg2, "Disrespectful", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg2, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg3, "Disruptive", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg3, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg4, "Property Distruction", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg4, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg5, "Threatening", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg5, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg6, "Obsenity", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg6, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg7, "Physical Aggression", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg7, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg8, "Verbal Aggression", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg8, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg9, "AWOL", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg9, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg10, "Sleeping", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg10, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg11, "Provoking/Mocking", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg11, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg12, "Self-Injurious", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg12, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg13, "Repeat Offense", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg13, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg14, "B.I.P. Goal", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg14, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg15, "Tardy", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg15, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :neg16, "Other", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:neg16, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :cor1, "Time Away", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:cor1, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :cor2, "Time Out", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:cor2, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :cor3, "Seclusion", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:cor3, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :cor4, "Restraint", :class => "control-label" %>
	<div class="controls">
		<%= f.select(:cor4, options_for_select([['0', 0], ['1', 1]]))  %>
	</div>
</div>
<div class="control-group">
	<%= f.label :record_time, "Behavior Record Time", :class => "control-label" %>
	<div class="controls">
		<%= f.time_select :record_time, { ampm: true, default: @today }%>
	</div>
</div>


app/views/behaviors/create.js.erb
console.log('Ajax worked!')
$(window.location.replace("/students/<%= @student.id %>"))

app/views/behaviors/edit.html.erb
<% provide(:title, "Edit behavior") %>
<h1>Update this behavior</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@behavior) do |f| %>
			<%= render 'fields', f: f %>
			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<% end %>

		
	</div>
</div>

app/views/behaviors/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HandsOnTable Test</title>
  <script src="../assets/javascript/jquery.min.js"></script>
  <script src="../assets/javascript/jquery.handsontable.full.js"></script>
  <link rel="stylesheet" type="text/css" media="screen" href="../assets/stylesheets/jquery.handsontable.full.css">
</head>
<body>
<div><h1>Top of Page</h1></div>
<div id="exampleGrid" class="handsontable"></div>
<div><h2>Below the table</h2></div>
<script type="text/javascript">
var myData = [
   ["", "Kia", "Nissan", "Toyota", "Honda"],
   ["2008", 10, 11, 12, 13],
   ["2009", 20, 11, 14, 13],
   ["2010", 30, 15, 12, 13]
   ];

$("#exampleGrid").handsontable({
   data: myData,
   startRows: 5,
   startCols: 5,
   minSpareCols: 1,
   //always keep at least 1 spare row at the right
   minSpareRows: 1,
   //always keep at least 1 spare row at the bottom,
   rowHeaders: true,
   colHeaders: true,
   contextMenu: true
});
</script>
</body>
</html>

app/views/behaviors/new.html.erb
<% provide(:title, "Record Behavior for "+@student.name) %>
<h3>Record Behavior for <%= link_to @student.name, @student %></h3>
<ul class=" nav nav-tabs">
	<li class="active" id="behaviorNewTab1">
		<%= link_to "Single Behavior Today", new_single_today_behaviors_path, remote: true %>
	</li>
	<li id="behaviorNewTab2">
		<%= link_to "Whole Day Behaviors", new_whole_day_behaviors_path, remote: true %>
	</li>
	<li id="behaviorNewTab3">
		<%= link_to "Single Behavior Choose Day", new_single_choose_behaviors_path, remote: true %>
	</li>
</ul>

<div id="behaviorNewContent">
	<%= render 'single_today_new' %>
</div>


app/views/behaviors/newOLD2.html.erb

<div class="row">
	<div class="span6 offset3">
		<table class="table table-striped table-condensed">
	<tr>
		<th>Time</th>
		<th>Positive</th>
		<th>Negative1</th>
		<th>Negative2</th>
		<th>Correction</th>
		<th></th>
	</tr>
	
	<tr>
		<td>7:50 - 9:18</td>
		<td>1</td>
		<td>0</td>
		<td>0</td>
		<td>0</td>
		<td><%= link_to "Edit", '#' %></td>
	</tr>
	<tr>
		<td>9:18 - 10:46</td>
		<td>1</td>
		<td>0</td>
		<td>0</td>
		<td>0</td>
		<td><%= link_to "Edit", '#' %></td>
	</tr>
	<tr>
		<td>10:46 - 12:14</td>
		<td>1</td>
		<td>0</td>
		<td>0</td>
		<td>0</td>
		<td><%= link_to "Edit", '#' %></td>
	</tr>
	<tr>
		<td>12:14 - 1:42</td>
		<td>1</td>
		<td>0</td>
		<td>0</td>
		<td>0</td>
		<td><%= link_to "Edit", '#' %></td>
	</tr>
	<tr>
		<td>1:42 - 3:10</td>
		<td>1</td>
		<td>0</td>
		<td>0</td>
		<td>0</td>
		<td><%= link_to "Edit", '#' %></td>
	</tr>
</table>
	</div>
</div>

app/views/behaviors/newOld.html.erb

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@behavior) do |f| %>
			<%= render 'fields', f: f %>
			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/behaviors/new_single_today.js.erb
$("#behaviorNewTab1").addClass("active");
$("#behaviorNewTab2").removeClass("active");
$("#behaviorNewTab3").removeClass("active");
$("#behaviorNewContent").html("<%= escape_javascript(render('single_today_new')) %>");