config/routes.rb
DailyBehavior::Application.routes.draw do
  
  resources :student_data
  resources :prospects
  resources :behaviors do
    collection do
      get 'new_single_today'
      get 'new_whole_day'
      get 'new_single_choose'
    end
  end

  resources :students do
    member do
      get 'show_table'
      get 'show_graph'
    end
  end
  resources :password_resets
  resources :users
  resources :sessions,   only: [:new, :create, :destroy]

  root :to => 'static_pages#home'
  match 'help',    to: 'static_pages#help',    via: 'get'
  match 'about',   to: 'static_pages#about',   via: 'get'
  match 'contact', to: 'static_pages#contact', via: 'get'
  match 'signup',  to: 'prospects#new',        via: 'get'

  match 'signin',  to: 'sessions#new',         via: 'get'
  match 'signout', to: 'sessions#destroy',     via: 'delete'

end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :email, :name, :password, :password_confirmation
  has_many :students
  before_save { self.email = email.downcase }
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  					uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def send_password_reset
    self.update_attribute(:password_reset_token, SecureRandom.urlsafe_base64) 
    self.update_attribute(:password_reset_sent_at, Time.zone.now)
    
    UserMailer.password_reset(self).deliver
  end

  def User.new_remember_token
  	SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
  	Digest::SHA1.hexdigest(token.to_s)
  end

  def feed
    # This is preliminary. See "Following users" for the full implementation.
    Micropost.where("user_id = ?", id)
  end

  private

  	def create_remember_token
  		self.remember_token = User.encrypt(User.new_remember_token)
  	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy, :new, :create]
  
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
  	@user = User.find(params[:id])
    @students = @user.students.paginate(page: params[:page])
  end

  def edit
   
  end

  def update
   
    if @user.update_attributes(user_params)
      # Handle a successfuol update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)		
  	if @user.save
      sign_in @user
  		flash[:success] = "Welcome to the Sample App!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user?(@user)
      flash[:error] = "You cannot delete yourself!"
      redirect_to users_url
    else
      @user.destroy
      flash[:success] = "User deleted."
      redirect_to users_url
    end
  end

  private

  	def user_params
  		params.require(:user).permit(:name, :email, :password, 
  									:password_confirmation)
  	end

    # Before filters

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)      
    end

    def admin_user
      redirect_to(root_url) unless  current_user.admin?
    end


end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
	def  gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, "Confirm Password" %>
<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 52 %>
	<%= link_to user.name, user %>
	<!--
	<# % if current_user.admin? && !current_user?(user) %>
		| <# %= link_to "delete", user, method: :delete, data: { confirm: "You sure?" } %>
	<# % end %>
-->
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'fields', f: f %>
			<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
		<% end %>

		<%= gravatar_for @user %>
		<a href="http://gravatar.com/emails" target="_blank">change</a>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Create new user') %>
<h1>Create a new user</h1>

<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>
			<%= render 'fields', f: f %>
			<%= f.submit "Create User", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="span4">
		<section>
			<h1>
				<%= gravatar_for @user %>
				<%= @user.name %>
			</h1>
		</section>
		<% if current_user?(@user) %>
			<section>
				<p><%= link_to "Create new student", new_student_path %></p>
			</section>
			<section>
				<% if current_user.admin? %>
					<h2>Admin Tools</h2>
					<p><%= link_to "View Prospects", prospects_path %></p>
					<p><%= link_to "Create New User", new_user_path %></p>
				<% end %>
			</section>
		<% end %>
	</aside>
	<div class="span8">
		<% if @user.students.any? %>
      		<h3>Students (<%= @user.students.count %>)</h3>
      		<ol class="students">
        		<%= render @students %>
      		</ol>
      		<%= will_paginate @students %>
    	<% end %>
	</div>
</div>